### PR TITLE
fix: forge init deploys hidden template files

### LINKED ISSUE #28: forge init silently skips hidden template files (.pre-commit-config.yaml, .gitignore, .gitattributes)
## Problem

\`forge init\` skips all hidden files in \`templates/init/\` except \`.githooks\` and \`.github\`. As a result, files like \`.pre-commit-config.yaml\`, \`.gitignore\`, and \`.gitattributes\` — which exist in the embedded template — are silently dropped from every newly-initialized module.

Surfaced when forge-gm CI failed on \`prek\` because no \`.pre-commit-config.yaml\` was present, despite the file living in \`templates/init/.pre-commit-config.yaml\` since #14 (2026-04-06).

## Location

\`src/cli/init/mod.rs\` lines 19-26:

\`\`\`rust
for filename in InitTemplates::iter() {
    // Skip hidden files like .DS_Store that might be in the templates directory
    if filename.starts_with('.')
        && !filename.starts_with(".githooks")
        && !filename.starts_with(".github")
    {
        continue;
    }
    ...
}
\`\`\`

The intent (per the comment) was to skip OS junk like \`.DS_Store\`. The implementation is a near-total allowlist that drops every dotfile.

## Impact

Every module created by \`forge init\` is missing:

- \`.pre-commit-config.yaml\` — \`prek\` / pre-commit hooks fail
- \`.gitignore\` — common build artifacts not ignored
- \`.gitattributes\` — line-ending and diff settings not applied

Confirmed missing in forge-gm; likely missing in every other init-bootstrapped module.

## Proposed fix

Replace the near-total dotfile allowlist with a small blocklist of OS junk:

\`\`\`rust
const SKIP_PATTERNS: &[&str] = &[".DS_Store", ".idea/", ".vscode/"];

for filename in InitTemplates::iter() {
    if SKIP_PATTERNS.iter().any(|pattern| filename.contains(pattern)) {
        continue;
    }
    ...
}
\`\`\`

Or whatever blocklist scope makes sense — the principle is opt-out, not opt-in.

## Workaround

Manually copy \`.pre-commit-config.yaml\` (and any other dotfile) from \`forge-cli/templates/init/\` into the new module after running \`forge init\`.

## Test

The existing init test (\`src/cli/init/tests.rs:15\`) only asserts \`.githooks/pre-commit\` exists. Extend it to assert \`.pre-commit-config.yaml\`, \`.gitignore\`, and \`.gitattributes\` are present too — these would have caught this.

### PR DESCRIPTION
**Pull request by N4M3Z**
## Summary

Closes #28.

`forge init`'s dotfile allowlist permitted only `.githooks/*` and `.github/*`, silently dropping every other hidden file from `templates/init/`:

- `.pre-commit-config.yaml`
- `.gitattributes`
- `.gitleaks.toml`
- `.gitlab-ci.yml`

Surfaced when forge-gm CI failed on `prek` because `forge init` had never deployed the `.pre-commit-config.yaml` despite it living in the embedded templates since #14.

## Fix

Replace the near-total dotfile allowlist with an OS-junk blocklist by basename — `.DS_Store`, `Thumbs.db`, `Desktop.ini`, and macOS `._*` resource forks. Every other template file is deployed.

## Test plan

- [x] `cargo test` — 408 passed (3 new init tests covering the blocklist + the deployment)
- [x] `cargo clippy -- -D warnings` clean
- [x] `cargo fmt --check` clean
- [x] `make validate` clean
- [x] `forge init --target /tmp/scratch && ls -la /tmp/scratch` shows `.pre-commit-config.yaml`, `.gitattributes`, `.gitleaks.toml`, `.gitlab-ci.yml`

### CODE REVIEW

File: src/cli/init/mod.rs [hunk 1]
```diff
@@ -114,6 +110,19 @@ pub fn execute(path: &str) -> Result<ActionResult, Error> {
     Ok(result)
 }
 
+/// Drop OS-junk files that find their way into the templates directory but
+/// should not land in scaffolded modules. Everything else (including dotfiles
+/// like `.pre-commit-config.yaml`, `.gitattributes`, `.gitleaks.toml`) is
+/// deployed.
+fn is_os_junk(filename: &str) -> bool {
+    const SKIP: &[&str] = &[".DS_Store", "Thumbs.db", "Desktop.ini"];
```
Comment (N4M3Z) [inline src/cli/init/mod.rs:118]: I'm sure there is a better way to do this than hardcoding, is there a lib?

**Comment by N4M3Z** [comment]
Researched. There is a [\`junk\`](https://docs.rs/junk/latest/junk/) crate that does exactly this — a Rust port of [sindresorhus/junk](https://github.com/sindresorhus/junk) (the canonical JS implementation).

I'd skip it. Reasons:

| Signal | Value |
| --- | --- |
| Last release | January 2020 (six years stale) |
| Total downloads | 4,861 |
| Recent downloads | 55 |
| API surface | `is(name) -> bool` and `not(name) -> bool` — same shape as my `is_os_junk` |
| JS original last release | April 2023 — also "feature-complete" |

The patterns this filters (`.DS_Store`, `Thumbs.db`, `._*`, etc.) haven't changed in years; the JS lib hasn't shipped a release in three years and the Rust port has been silent for six. Adopting an unmaintained six-year-old transitive dep for a 4-line function trades inline clarity for hidden risk — if a new junk pattern ever appears (unlikely), an unmaintained crate won't catch it either.

Keeping the inline blocklist as-is. If we ever feel the patterns are growing, the migration to `junk` (or a fork) is one find-and-replace.

Sources:
- [junk crate (Rust)](https://docs.rs/junk/latest/junk/)
- [sindresorhus/junk (JS original)](https://github.com/sindresorhus/junk)
- [crates.io/junk metadata](https://crates.io/crates/junk)

File: src/cli/init/mod.rs (hunk 1 above)
Comment (N4M3Z) [reply src/cli/init/mod.rs:118]: Researched: there's a [`junk` crate](https://docs.rs/junk/latest/junk/) (Rust port of `sindresorhus/junk`), but it's been silent since January 2020 (six years), 4,861 total downloads, 55 recent. The JS original last released April 2023 — both effectively feature-complete. The patterns (`.DS_Store`, `Thumbs.db`, `._*`) haven't changed in years; adopting an unmaintained six-year-old dep for a 4-line function trades inline clarity for hidden risk. Keeping the hardcoded blocklist; if patterns ever grow, swap-in is one find-and-replace. Top-level comment with full sourcing: #35 (issuecomment-4330752943).
